import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

// jsdom does not implement ResizeObserver (used by cmdk and other UI libs)
global.ResizeObserver = class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
};

// jsdom does not implement scrollIntoView (used by cmdk)
Element.prototype.scrollIntoView ??= () => {};

// ---------------------------------------------------------------------------
// Global next-intl mock for unit tests.
//
// Components use useTranslations(namespace) which returns t(key).
// The mock returns the Italian string for each key so all existing tests that
// check for Italian UI text continue to pass without wrapping in
// NextIntlClientProvider.
// ---------------------------------------------------------------------------
const _italianStrings: Record<string, Record<string, string>> = {
  common: {
    open_menu: 'Apri menu',
    search_placeholder: 'Cerca...',
    search_label: 'Apri ricerca (Cmd+K)',
    notifications: 'Notifiche',
    expand_sidebar: 'Espandi barra laterale',
    collapse_sidebar: 'Comprimi barra laterale',
    expand: 'Espandi',
    collapse: 'Comprimi',
    mobile_nav_label: 'Menu di navigazione',
    organizations: 'Organizzazioni',
    create_new_org: 'Crea nuova organizzazione',
    org_switcher_label: 'Cambia organizzazione',
    default_org_name: 'Organizzazione',
    marketing_nav_label: 'Navigazione marketing',
    marketing_sign_in: 'Accedi',
    marketing_legal_nav_label: 'Link legali',
    marketing_copyright: '© {year} VoiceFlow. Tutti i diritti riservati.',
    marketing_privacy: 'Privacy Policy',
    marketing_terms: 'Termini di Servizio',
    marketing_cookies: 'Cookie Policy',
    marketing_dpa: 'DPA',
    command_palette_title: 'Ricerca rapida',
    command_palette_description: "Cerca azioni e naviga nell'applicazione",
    command_palette_placeholder: 'Cerca azioni, contatti, campagne…',
    command_palette_no_results: 'Nessun risultato trovato.',
    command_palette_nav_group: 'Navigazione',
    command_palette_actions_group: 'Azioni rapide',
    command_palette_contacts_group: 'Contatti',
    command_palette_campaigns_group: 'Campagne',
    command_palette_scripts_group: 'Script',
    action_create_campaign: 'Crea campagna',
    action_upload_contacts: 'Carica contatti',
    action_topup_credit: 'Ricarica credito',
    action_goto_settings: 'Vai a impostazioni',
    confirm: 'Conferma',
    cancel: 'Annulla',
    loading: 'Attendere…',
    error_generic: 'Si è verificato un errore. Riprova.',
  },
  nav: {
    dashboard: 'Dashboard',
    campaigns: 'Campagne',
    contacts: 'Contatti',
    scripts: 'Script',
    credit: 'Credito',
    settings: 'Impostazioni',
    primary_nav_label: 'Navigazione principale',
  },
  dashboard: {
    greeting: 'Dashboard',
    period_aria_label: 'Seleziona periodo',
    period_today: 'Oggi',
    period_7d: 'Ultimi 7 giorni',
    period_30d: 'Ultimi 30 giorni',
    period_month: 'Mese corrente',
    period_prev_month: 'Mese scorso',
    period_summary_today: 'Dati di oggi',
    period_summary_7d: 'Dati degli ultimi 7 giorni',
    period_summary_30d: 'Dati degli ultimi 30 giorni',
    period_summary_month: 'Dati del mese corrente',
    period_summary_prev_month: 'Dati del mese scorso',
    kpi_section_label: 'Indicatori chiave',
    kpi_calls_completed: 'Chiamate completate',
    kpi_qualified_leads: 'Lead qualificati',
    kpi_appointments: 'Appuntamenti fissati',
    kpi_credit_residual: 'Credito residuo',
    kpi_credit_minutes: '≈ {minutes} minuti rimanenti',
    kpi_trend_14d: 'Trend ultimi 14 giorni',
    sparkline_aria_calls: 'Andamento chiamate completate negli ultimi 14 giorni',
    sparkline_aria_leads: 'Andamento lead qualificati negli ultimi 14 giorni',
    sparkline_aria_appointments: 'Andamento appuntamenti negli ultimi 14 giorni',
    trend_title: 'Chiamate per giorno per esito',
    trend_no_data: 'Nessuna chiamata nel periodo selezionato',
    trend_aria_label: 'Grafico chiamate per giorno ({count} barre)',
    legend_appointmentBooked: 'Appuntamento',
    legend_completed: 'Completata',
    legend_notInterested: 'Non interessato',
    legend_voicemail: 'Segreteria',
    legend_failed: 'Fallita',
    active_campaigns_title: 'Campagne attive',
    active_campaigns_empty: 'Nessuna campagna in esecuzione',
    see_all: 'Vedi tutte',
    campaign_progress: '{completed}/{total} chiamate',
    campaign_appointments: '{count} appuntamenti',
    recent_appointments_title: 'Ultimi appuntamenti fissati',
    recent_appointments_empty: 'Ancora nessun appuntamento',
    alerts_title: 'Avvisi',
    alerts_empty: 'Tutto in ordine',
    alert_low_credit: 'Credito basso: solo {minutes} minuti rimanenti',
    alert_cli_cooldown: '{count} numeri in cooldown',
    alert_disclosure_failure: '{count} chiamate con problemi di disclosure AI Act',
    onboarding_title: 'Inizia in 3 semplici passi',
    onboarding_description: 'Configura la tua prima campagna in pochi minuti.',
    onboarding_step_contacts_title: 'Carica contatti',
    onboarding_step_contacts_desc: 'Importa la tua lista contatti tramite file CSV.',
    onboarding_step_contacts_cta: 'Carica contatti',
    onboarding_step_script_title: 'Configura script',
    onboarding_step_script_desc:
      'Personalizza il messaggio del tuo agente AI partendo da un template.',
    onboarding_step_script_cta: 'Configura script',
    onboarding_step_campaign_title: 'Crea campagna',
    onboarding_step_campaign_desc:
      'Avvia la tua prima campagna outbound combinando lista e script.',
    onboarding_step_campaign_cta: 'Crea campagna',
  },
  auth: {
    user_menu_label: 'Menu utente',
    profile: 'Profilo',
    settings: 'Impostazioni',
    language: 'Lingua',
    theme: 'Tema',
    sign_out: 'Esci',
    default_user: 'Utente',
    theme_light: 'Chiaro',
    theme_dark: 'Scuro',
    theme_system: 'Sistema',
    locale_it: 'Italiano',
    locale_en: 'English',
    sign_in: 'Accedi',
    sign_in_description: 'Accedi al tuo account',
    sign_up: 'Registrati',
    email: 'Email',
    already_have_account: 'Hai già un account?',
    no_account_yet: 'Non hai ancora un account?',
    magic_link_title: 'Accedi',
    magic_link_description: 'Inserisci la tua email e ti invieremo un link di accesso',
    send_link: 'Invia link di accesso',
    signup_title: 'Crea account',
    signup_description: 'Inserisci la tua email per creare un nuovo account',
    verify_title: 'Controlla la tua email',
    verify_description: 'Abbiamo inviato un link di accesso a {email}. Clicca sul link per accedere.',
    verify_description_generic: 'Ti abbiamo inviato un link di accesso. Controlla la tua email e clicca sul link.',
    back_to_login: 'Torna al login',
    email_required: "L'email è obbligatoria",
    email_invalid: 'Inserisci un indirizzo email valido',
    link_sent: 'Link inviato! Controlla la tua casella.',
    sending: 'Invio in corso…',
  },
  contacts: {
    title: 'Contatti',
    new_contact: 'Nuovo contatto',
    no_contacts: 'Nessun contatto trovato',
    import_contacts: 'Importa contatti',
    export_contacts: 'Esporta contatti',
    first_name: 'Nome',
    last_name: 'Cognome',
    phone: 'Telefono',
    email: 'Email',
    opted_out: 'Ha rinunciato',
    last_called: 'Ultima chiamata',
    upload_title: 'Importa contatti',
    upload_description: 'Carica un file CSV per importare i contatti nella tua organizzazione',
    step_file: 'File',
    step_mapping: 'Mappatura colonne',
    step_compliance: 'Compliance',
    drop_file_here: 'Trascina il tuo file CSV qui',
    or_click_to_browse: 'o clicca per sfogliare',
    file_size_limit: 'Massimo 50 MB',
    accepted_formats: 'Accettati: CSV, Excel, testo',
    uploading: 'Caricamento in corso…',
    upload_complete: 'Caricamento completato',
    upload_error: 'Errore nel caricamento',
    auto_detected_columns: 'Colonne rilevate automaticamente',
    map_columns_title: 'Mappa colonne',
    map_columns_description: 'Assegna le colonne del tuo CSV ai campi corretti del contatto',
    preview_rows: 'Anteprima prime righe',
    column_phone: 'Colonna telefono',
    column_first_name: 'Colonna nome',
    column_last_name: 'Colonna cognome',
    column_email: 'Colonna email',
    not_mapped: 'Non mappato',
    consent_basis_label: 'Base giuridica del trattamento',
    consent_basis_consent: 'Consenso esplicito',
    consent_basis_legitimate_interest: 'Legittimo interesse',
    consent_basis_existing_customer: 'Cliente esistente',
    contact_type_label: 'Tipo di contatto',
    contact_type_b2c: 'B2C (privati)',
    contact_type_b2b: 'B2B (aziende)',
    consent_evidence_label: 'Evidenza del consenso (opzionale)',
    consent_evidence_placeholder: 'es. iscritto tramite modulo web il 01/01/2024',
    disclaimer_text: 'Confermo di avere base giuridica per contattare questi numeri',
    disclaimer_required: 'Devi accettare la dichiarazione per procedere',
    phone_column_required: 'La colonna telefono è obbligatoria',
    submit_import: 'Avvia importazione',
    submitting_import: 'Avvio in corso…',
    import_started: 'Importazione avviata con successo',
    back: 'Indietro',
    next: 'Avanti',
    list_detail_back: 'Torna ai contatti',
    list_source_csv_upload: 'Caricamento CSV',
    list_source_api: 'API',
    list_source_zapier: 'Zapier',
    list_total_contacts: 'Totale',
    list_valid_contacts: 'Validi',
    list_parsing_title: 'Importazione in corso',
    list_parsing_description: 'Il tuo CSV è in fase di elaborazione. Potrebbe richiedere alcuni minuti.',
    list_failed_title: 'Importazione fallita',
    list_failed_description: 'Nessun contatto valido trovato nel file.',
    list_errors_download: 'Scarica report errori',
    list_errors_loading: 'Caricamento…',
    list_errors_not_found: 'Report errori non trovato',
    list_contacts_count: '{count} contatti',
    col_name: 'Nome',
    col_phone: 'Telefono',
    col_email: 'Email',
    col_opt_out: 'Opt-out',
    col_rpo: 'RPO',
    col_actions: 'Azioni',
    filter_opt_out: 'Con opt-out',
    filter_all_opt_out: 'Tutti',
    filter_rpo_status: 'Stato RPO',
    filter_all_rpo: 'Tutti gli stati',
    filter_has_email: 'Con email',
    filter_search: 'Cerca per nome o telefono',
    rpo_clear: 'Conforme',
    rpo_blocked: 'Bloccato',
    rpo_unchecked: 'Non verificato',
    action_mark_opt_out: 'Segna come opt-out',
    action_opt_out_success: 'Contatto segnato come opt-out',
    action_delete: 'Elimina contatto',
    action_delete_title: 'Elimina contatto',
    action_delete_description: 'Il contatto verrà rimosso definitivamente da questa lista.',
    action_delete_success: 'Contatto eliminato',
    action_view_metadata: 'Vedi dati originali',
    action_bulk_delete_description: 'Elimina {count} contatti. Questa operazione non può essere annullata.',
    bulk_mark_opt_out: 'Segna come opt-out',
    bulk_delete: 'Elimina selezionati',
    bulk_selected: '{count} selezionati',
    bulk_opt_out_success: '{count} contatti segnati come opt-out',
    bulk_delete_success: '{count} contatti eliminati',
    export_selected: 'Esporta selezionati ({count})',
    no_contacts_in_list: 'Nessun contatto in questa lista',
    no_contacts_match: 'Nessun contatto corrisponde ai filtri',
    status_opted_out: 'Opt-out',
    status_active: 'Attivo',
    tab_lists: 'Liste',
    tab_all: 'Tutti i contatti',
    tab_opt_out: 'Opt-out',
    upload_new_list: 'Carica nuova lista',
    no_lists: 'Nessuna lista trovata',
    first_list_title: 'Nessuna lista contatti',
    first_list_desc: 'Carica la tua prima lista per iniziare a chiamare i tuoi contatti.',
    first_list_cta: 'Carica prima lista',
    list_col_name: 'Nome',
    list_col_source: 'Fonte',
    list_col_contacts: 'Contatti',
    list_col_status: 'Stato',
    list_col_created: 'Data creazione',
    all_contacts_title: 'Tutti i contatti',
    opt_out_title: 'Contatti con opt-out',
    add_contact_btn: 'Aggiungi contatto',
    add_contact_dialog_title: 'Aggiungi contatto manualmente',
    add_contact_phone_placeholder: '+39 333 1234567',
    add_contact_phone_invalid: 'Numero di telefono non valido',
    add_contact_success: 'Contatto aggiunto',
    add_contact_already_exists: 'Contatto già presente — dati aggiornati',
    add_contact_submitting: 'Salvataggio…',
    dnc_btn: 'Importa do-not-call',
    dnc_dialog_title: 'Importa lista do-not-call',
    dnc_dialog_description: 'Carica un CSV con un numero di telefono per riga. Nessun contatto viene creato — solo gli opt-out vengono registrati.',
    dnc_file_label: 'File CSV (un numero per riga)',
    dnc_paste_label: 'Oppure incolla i numeri',
    dnc_paste_placeholder: '+39 333 1234567\n+39 02 12345678\n…',
    dnc_submit: 'Importa',
    dnc_submitting: 'Importazione…',
    dnc_success: '{count} numeri aggiunti alla lista do-not-call',
    dnc_no_valid_numbers: 'Nessun numero valido trovato nel file',
    dnc_error: "Errore durante l'importazione",
    export_btn: 'Esporta CSV',
    export_exporting: 'Esportazione…',
    export_success: 'Esportazione completata — il download inizierà a breve',
    export_deferred: 'Esportazione avviata — riceverai una notifica al completamento',
    export_error: "Errore durante l'esportazione",
  },
  credit: {
    top_up: 'Ricarica',
    total_purchased: 'Totale acquistati',
    credit_balance_label: 'Saldo crediti',
    reserved_active_calls: 'Riservati (chiamate attive)',
    available: 'Disponibili',
    pill_aria_label: 'Saldo crediti: {minutes} minuti rimanenti',
    topup_title: 'Ricarica credito',
    topup_subtitle: 'Scegli il pacchetto più adatto alle tue esigenze',
    per_minute: '€{rate}/min',
    included_minutes_fmt: '{minutes} minuti',
    proceed_to_payment: 'Procedi al pagamento',
    processing: 'Elaborazione…',
    payment_cancelled: 'Pagamento annullato',
    recommended_test: 'Ideale per testare il servizio',
    recommended_starter: 'Concessionario piccolo',
    recommended_growth: 'Concessionario medio',
    recommended_scale: 'Grande concessionario o rete',
    vat_included: 'IVA inclusa',
    topup_success_title: 'Pagamento completato',
    topup_success_subtitle: 'Il tuo saldo è stato aggiornato. Puoi iniziare ad utilizzare i tuoi crediti.',
    topup_success_balance: '{minutes} minuti disponibili',
    topup_success_cta: 'Vai alla dashboard',
    topup_pending_title: 'Verifica pagamento in corso…',
    topup_pending_subtitle: 'Attendi mentre confermiamo il tuo pagamento.',
    topup_timeout_title: 'Pagamento in elaborazione',
    topup_timeout_message: 'Riceverai un\'email appena il pagamento è confermato.',
    topup_session_not_found: 'Sessione non trovata.',
    topup_back_to_topup: 'Torna alla ricarica',
    page_title: 'Credito',
    top_up_cta: 'Ricarica',
    balance_minutes: '{minutes} minuti',
    balance_cents: '€{euros}',
    package_pools_title: 'Pacchetti acquistati',
    pool_purchased_on: 'Acquistato il {date}',
    ledger_title: 'Storico movimenti',
    ledger_col_type: 'Tipo',
    ledger_col_description: 'Descrizione',
    ledger_col_delta: 'Importo',
    ledger_col_balance: 'Saldo dopo',
    ledger_col_date: 'Data',
    ledger_no_entries: 'Nessun movimento',
    filter_all_types: 'Tutti i tipi',
    filter_type_topup: 'Ricarica',
    filter_type_reservation: 'Prenotazione',
    filter_type_release: 'Rilascio',
    filter_type_charge: 'Addebito',
    filter_type_refund: 'Rimborso',
    filter_type_adjustment: 'Rettifica',
    filter_date_from: 'Da',
    filter_date_to: 'A',
    export_csv: 'Esporta CSV',
    ledger_col_invoice: 'Fattura',
    invoice_link: 'Scarica',
    ledger_count: '{count} movimenti',
  },
  table: {
    columns: 'Colonne',
    visible_columns: 'Colonne visibili',
    rows_per_page: 'Righe per pagina',
    rows_selected: '{selected} di {total} riga/e selezionata/e',
    total_rows: '{total} riga/e totali',
    page_of: 'Pagina {page} di {total}',
    first_page: 'Prima pagina',
    prev_page: 'Pagina precedente',
    next_page: 'Pagina successiva',
    last_page: 'Ultima pagina',
  },
  onboarding: {
    title: 'Configura la tua organizzazione',
    description: 'Raccontaci della tua organizzazione per iniziare.',
    name_label: 'Nome organizzazione',
    name_placeholder: 'Acme Corp',
    legal_name_label: 'Ragione sociale (opzionale)',
    legal_name_placeholder: 'Acme S.r.l.',
    vat_label: 'Partita IVA (opzionale)',
    vat_placeholder: '12345678901',
    country_label: 'Paese',
    country_it: 'Italia',
    dpa_label_before: 'Accetto il ',
    dpa_link_text: 'Accordo sul Trattamento dei Dati',
    submit: 'Crea organizzazione',
    submitting: 'Creazione in corso…',
    name_required: "Il nome dell'organizzazione è obbligatorio",
    name_too_long: 'Il nome deve essere al massimo 100 caratteri',
    vat_invalid: 'Partita IVA non valida (deve essere 11 cifre con checksum valido)',
    dpa_required: "Devi accettare l'Accordo sul Trattamento dei Dati",
  },
  settings: {
    title: 'Impostazioni',
    organization: 'Organizzazione',
    members: 'Membri',
    billing: 'Fatturazione',
    profile: 'Profilo',
    notifications: 'Notifiche',
    security: 'Sicurezza',
    invite_member: 'Invita membro',
    remove_member: 'Rimuovi membro',
    role_owner: 'Proprietario',
    role_admin: 'Amministratore',
    role_operator: 'Operatore',
    role_viewer: 'Visualizzatore',
    members_title: 'Membri',
    members_description: 'Gestisci i membri del team e i loro ruoli.',
    invite_dialog_title: 'Invita un membro del team',
    invite_email_label: 'Indirizzo email',
    invite_role_label: 'Ruolo',
    invite_submit: 'Invia invito',
    invite_submitting: 'Invio in corso…',
    change_role: 'Cambia ruolo',
    change_role_dialog_title: 'Cambia ruolo del membro',
    change_role_submit: 'Salva',
    remove_confirm_title: 'Rimuovi membro',
    remove_confirm_description:
      "Il membro perderà l'accesso all'organizzazione. Questa operazione non può essere annullata.",
    column_member: 'Membro',
    column_role: 'Ruolo',
    column_joined: 'Iscritto',
    column_last_login: 'Ultimo accesso',
    column_actions: 'Azioni',
    accepted_members_title: 'Membri attivi',
    pending_invites_title: 'Inviti in sospeso',
    no_members: 'Nessun membro attivo',
    no_pending_invites: 'Nessun invito in sospeso',
    last_login_never: 'Mai',
    invited_date: 'Invitato',
    member_actions_label: 'Azioni membro',
    org_title: 'Organizzazione',
    org_description: 'Gestisci le impostazioni della tua organizzazione.',
    org_info_id: 'ID organizzazione',
    org_info_created: 'Creata il',
    org_info_members: 'Membri',
    org_name_label: 'Nome organizzazione',
    org_legal_name_label: 'Ragione sociale (opzionale)',
    org_legal_name_placeholder: 'Acme S.r.l.',
    org_vat_label: 'Partita IVA (opzionale)',
    org_vat_placeholder: '12345678901',
    org_save_button: 'Salva modifiche',
    org_save_submitting: 'Salvataggio…',
    org_danger_zone_title: 'Zona pericolosa',
    org_danger_zone_description:
      "L'eliminazione dell'organizzazione è permanente e rimuoverà tutti i dati.",
    org_delete_button: 'Elimina organizzazione',
    org_delete_dialog_title: 'Elimina organizzazione',
    org_delete_dialog_description: 'Questo eliminerà logicamente "{name}".',
    org_delete_confirm_label: "Digita il nome dell'organizzazione per confermare",
    org_delete_submitting: 'Eliminazione…',
    billing_portal_title: 'Storico fatture',
    billing_portal_description: 'Accedi al portale di fatturazione.',
    billing_portal_button: 'Apri storico fatture',
    billing_portal_opening: 'Apertura in corso…',
  },
  notifications_settings: {
    title: 'Notifiche',
    description:
      'Scegli quali email vuoi ricevere da questa organizzazione. Le impostazioni sono per utente e per organizzazione.',
    save_success: 'Preferenza aggiornata',
    daily_report_label: 'Report giornaliero',
    daily_report_description:
      'Riepilogo email serale con i KPI del giorno e gli appuntamenti fissati.',
    appointment_booked_label: 'Appuntamento fissato',
    appointment_booked_description:
      'Notifica immediata ogni volta che una chiamata fissa un nuovo appuntamento.',
    qualified_lead_label: 'Lead qualificato',
    qualified_lead_description: 'Notifica quando un contatto viene qualificato come interessato.',
    low_credit_label: 'Credito basso',
    low_credit_description:
      'Avviso quando il credito residuo scende sotto la soglia di sicurezza.',
    campaign_completed_label: 'Campagna completata',
    campaign_completed_description:
      'Notifica al termine di una campagna con il riepilogo dei risultati.',
    weekly_summary_label: 'Riepilogo settimanale',
    weekly_summary_description:
      "Email del lunedì mattina con l'andamento della settimana precedente.",
  },
  compliance_settings: {
    title: 'Compliance e GDPR',
    description: 'Gestisci le richieste degli interessati e consulta la documentazione.',
    rights_title: "Diritti dell'interessato (GDPR)",
    rights_description:
      "Esporta tutti i dati di un contatto (Articolo 15) o richiedi la cancellazione (Articolo 17).",
    identifier_label: 'Telefono o email del contatto',
    identifier_placeholder: '+393331234567 oppure mario.rossi@example.com',
    identifier_hint:
      "Inserisci il numero in formato E.164 oppure l'indirizzo email associato al contatto.",
    export_button: 'Esporta dati',
    export_submitting: 'Esportazione in corso…',
    erase_button: 'Cancella dati',
    export_success: 'Esportazione pronta',
    subject_not_found: "Nessun contatto corrisponde all'identificatore fornito",
    export_ready_title: 'Archivio pronto',
    export_ready_expires: 'Scade il {date}',
    export_ready_download: 'Scarica archivio ZIP',
    history_title: 'Storico richieste GDPR',
    history_description: 'Esportazioni e cancellazioni effettuate per la tua organizzazione.',
    history_refresh: 'Aggiorna',
    history_refreshing: 'Aggiornamento…',
    history_empty_title: 'Nessuna richiesta',
    history_empty_description: 'Le richieste GDPR effettuate compariranno qui.',
    history_action_export: 'Esportazione (Art. 15)',
    history_action_erasure: 'Cancellazione (Art. 17)',
    history_actor_system: 'Sistema',
    history_export_summary: '{calls} chiamate incluse',
    history_erasure_summary: 'Numero: {phone}',
    erase_dialog_title: 'Conferma cancellazione GDPR',
    erase_dialog_description:
      'Questa operazione cancella in modo permanente i dati del contatto.',
    erase_confirm_phone_label: 'Digita il numero di telefono del contatto per confermare',
    erase_confirm_phone_hint:
      'Deve corrispondere esattamente al numero E.164 registrato nel contatto.',
    erase_reason_label: 'Motivo della richiesta',
    erase_reason_placeholder: "es. Richiesta scritta dell'interessato del 08/05/2026",
    erase_dialog_cancel: 'Annulla',
    erase_dialog_confirm: 'Conferma cancellazione',
    erase_dialog_submitting: 'Cancellazione in corso…',
    erase_success: 'Cancellazione completata',
    erase_mismatch: 'Il numero inserito non corrisponde al contatto.',
    docs_title: 'Documentazione',
    docs_description: 'Documenti legali della piattaforma.',
    docs_dpa: 'Accordo sul Trattamento dei Dati (DPA)',
    docs_privacy: 'Informativa sulla privacy',
    docs_terms: 'Termini di servizio',
    docs_cookie: 'Cookie policy',
    dpa_banner_title: 'Aggiornamento DPA richiesto',
    dpa_banner_description_outdated:
      "L'Accordo sul Trattamento dei Dati è stato aggiornato dalla versione {acceptedVersion} alla versione {currentVersion}. Conferma la nuova versione per continuare ad utilizzare la piattaforma.",
    dpa_banner_description_never:
      "La tua organizzazione non ha ancora accettato l'Accordo sul Trattamento dei Dati (versione {currentVersion}). Conferma per continuare ad utilizzare la piattaforma.",
    dpa_banner_accept: 'Accetta DPA',
    dpa_banner_accepting: 'Accettazione…',
    dpa_banner_accept_success: 'Accordo accettato',
  },
  audit_log: {
    title: 'Registro audit',
    description: 'Tracciamento di tutte le azioni significative svolte nella tua organizzazione.',
    filters_title: 'Filtri',
    filter_action_label: 'Prefisso azione',
    filter_action_placeholder: 'es. compliance.',
    filter_from_label: 'Da',
    filter_to_label: 'A',
    filter_actor_label: 'ID utente',
    filter_actor_placeholder: "UUID dell'utente",
    apply_filters: 'Applica',
    applying: 'Applicazione…',
    reset_filters: 'Reimposta',
    export_csv: 'Esporta CSV',
    exporting: 'Esportazione…',
    export_success: '{count} righe esportate',
    export_success_truncated: 'Esportate le {count} righe più recenti (limite raggiunto)',
    empty_title: 'Nessuna voce di audit',
    empty_description: 'Non sono ancora state registrate azioni che corrispondano ai filtri.',
    column_timestamp: 'Data e ora',
    column_actor: 'Attore',
    column_action: 'Azione',
    column_subject: 'Oggetto',
    column_details: 'Dettagli',
    details_show: 'Mostra',
    details_hide: 'Nascondi',
    actor_system: 'Sistema',
    actor_webhook: 'Webhook',
    actor_unknown: 'Sconosciuto',
    load_more: 'Carica altri',
    loading_more: 'Caricamento…',
  },
  integrations: {
    pat_title: 'Token di Accesso Personale',
    pat_description: 'Token per accesso programmatico all\'API.',
    create_token: 'Crea token',
    create_token_dialog_title: 'Crea Token di Accesso Personale',
    token_name_label: 'Nome del token',
    token_name_placeholder: 'es. Integrazione Zapier',
    create_token_submit: 'Crea',
    create_token_submitting: 'Creazione in corso…',
    token_created_title: 'Token creato',
    token_created_description: 'Copia il token ora. Non potrai vederlo di nuovo.',
    copy_token: 'Copia token',
    revoke: 'Revoca',
    column_name: 'Nome',
    column_prefix: 'Prefisso',
    column_scopes: 'Ambiti',
    column_last_used: 'Ultimo utilizzo',
    column_created: 'Creato',
    column_actions: 'Azioni',
    no_tokens: 'Nessun token di accesso personale',
    never_used: 'Mai',
  },
  scripts: {
    title: 'Script',
    templates_title: 'Template disponibili',
    your_scripts_title: 'I tuoi script',
    no_scripts: 'Nessuno script configurato — inizia da uno dei nostri template',
    create_from_template: 'Crea da questo template',
    col_name: 'Nome',
    col_template: 'Template',
    col_updated: 'Ultimo aggiornamento',
    col_actions: 'Azioni',
    action_edit: 'Modifica',
    action_delete: 'Elimina',
    delete_title: 'Elimina script',
    delete_description:
      'Lo script verrà eliminato definitivamente. Le campagne che usano questo script devono essere completate o annullate prima.',
    delete_success: 'Script eliminato',
    delete_error_referenced:
      'Questo script è utilizzato da campagne attive. Completale o annullale prima.',
    template_lead_reactivation_desc: 'Riattivazione dei lead inattivi con proposta di appuntamento',
    template_appointment_confirm_desc: 'Conferma, modifica o cancellazione degli appuntamenti esistenti',
    template_car_renewal_desc: 'Proposta di rinnovo del veicolo ai clienti con auto di un certo numero di anni',
    template_post_sale_followup_desc: 'Follow-up post-vendita per raccogliere soddisfazione e prenotare tagliando',
    template_csi_survey_desc: 'Questionario di soddisfazione cliente per la casa madre',
    new_script_title: 'Nuovo script',
    step_select_template: 'Seleziona template',
    step_configure: 'Configura variabili',
    field_script_name_label: 'Nome script',
    field_script_name_placeholder: 'es. Riattivazione Lead Primavera 2026',
    field_required_error: 'Campo obbligatorio',
    optional_label: '(opzionale)',
    add_slot: 'Aggiungi slot',
    remove_slot: 'Rimuovi',
    preview_title: 'Anteprima prompt',
    preview_system_prompt_label: 'System prompt',
    preview_first_message_label: 'Primo messaggio',
    preview_placeholder_hint: "Completa i campi per visualizzare l\u2019anteprima completa",
    save_script: 'Salva script',
    saving_script: 'Salvataggio\u2026',
    save_success: 'Script salvato con successo',
    back_to_templates: 'Scegli un altro template',
    select_this_template: 'Usa questo template',
    edit_script_title: 'Modifica script',
    edit_script_back: 'Torna agli script',
    template_label: 'Template',
    voice_override_label: 'Voce personalizzata (ID)',
    voice_override_placeholder: 'es. voice-abc-123 (lascia vuoto per la voce predefinita)',
    voice_override_hint: 'Sostituisce la voce predefinita del template. Popolato nel piano 08.',
    save_changes: 'Salva modifiche',
    saving_changes: 'Salvataggio\u2026',
    save_changes_success: 'Modifiche salvate',
    copy_script: 'Copia per modifiche',
    copy_success: 'Script copiato',
    use_in_campaign: 'Usa in nuova campagna',
    not_found: 'Script non trovato',
    voice_sample_listen: 'Ascolta un esempio',
    voice_sample_loading: 'Generazione in corso\u2026',
    voice_sample_error: 'Impossibile generare il campione audio',
    required_fields: 'Campi richiesti',
    test_call_button: 'Chiamami ora',
    test_call_dialog_title: 'Chiama di prova',
    test_call_dialog_description: 'Inserisci il tuo numero di telefono italiano per ricevere una chiamata di prova con questo script. Limite: 10 chiamate di prova al giorno per organizzazione.',
    test_call_phone_label: 'Numero di telefono',
    test_call_phone_placeholder: '+393331234567',
    test_call_phone_invalid: 'Inserisci un numero di telefono italiano in formato E.164 (es. +393331234567)',
    test_call_submit: 'Avvia chiamata',
    test_call_submitting: 'Avvio in corso\u2026',
    test_call_success: 'Chiamata di prova avviata (ID: {callId})',
    test_call_rate_limit: 'Limite di 10 chiamate di prova al giorno raggiunto. Riprova domani.',
    test_call_error: 'Impossibile avviare la chiamata di prova',
  },
  campaigns: {
    title: 'Campagne',
    new_campaign: 'Nuova campagna',
    no_campaigns: 'Nessuna campagna trovata',
    status_draft: 'Bozza',
    status_active: 'Attiva',
    status_paused: 'In pausa',
    status_completed: 'Completata',
    status_cancelled: 'Cancellata',
    start_date: 'Data inizio',
    end_date: 'Data fine',
    total_contacts: 'Contatti totali',
    called: 'Chiamati',
    answered: 'Risposto',
    conversion_rate: 'Tasso di conversione',
    new_campaign_title: 'Nuova campagna',
    back_to_campaigns: 'Torna alle campagne',
    step_script: 'Script',
    step_contact_list: 'Lista contatti',
    step_schedule: 'Pianifica',
    no_scripts_title: 'Nessuno script disponibile',
    no_scripts_hint: 'Crea uno script prima di avviare una campagna.',
    create_script_link: 'Crea script',
    select_script_btn: 'Usa questo script',
    script_template_label: 'Template',
    no_contact_lists_title: 'Nessuna lista contatti',
    no_contact_lists_hint: 'Carica una lista contatti prima di avviare una campagna.',
    upload_contact_list_link: 'Carica lista',
    select_list_btn: 'Usa questa lista',
    valid_contacts_count: '{count} contatti validi',
    field_name_label: 'Nome campagna',
    field_name_placeholder: 'es. Riattivazione Lead Maggio 2026',
    field_name_required: 'Il nome è obbligatorio',
    field_scheduled_start_label: 'Data e ora di inizio (opzionale)',
    field_scheduled_start_hint: 'Lascia vuoto per avviare immediatamente dopo la creazione',
    field_time_window_label: 'Finestra oraria chiamate',
    field_time_window_start_label: 'Inizio',
    field_time_window_end_label: 'Fine',
    field_concurrency_label: 'Chiamate simultanee',
    field_concurrency_hint: 'Numero massimo di chiamate attive in parallelo (1\u201320)',
    cost_summary_title: 'Stima costi',
    cost_expected_label: 'Costo atteso',
    cost_max_label: 'Costo massimo (importo riservato)',
    cost_no_billing_rate: 'Acquista crediti per visualizzare la stima dei costi.',
    credit_balance_label: 'Saldo crediti',
    credit_insufficient_warning: 'Saldo insufficiente per coprire il costo massimo della campagna.',
    selected_script_label: 'Script selezionato',
    selected_list_label: 'Lista selezionata',
    btn_back: 'Indietro',
    btn_next: 'Avanti',
    btn_launch: 'Avvia campagna',
    btn_save_scheduled: 'Salva come pianificata',
    btn_submitting: 'In corso\u2026',
    create_success: 'Campagna creata',
    launch_success: 'Campagna avviata',
    error_no_credit: 'Credito insufficiente per avviare la campagna',
    error_no_eligible: 'Nessun contatto idoneo nella lista selezionata',
    error_no_billing_rate: 'Nessun pacchetto crediti attivo. Acquista crediti prima di avviare.',
    error_not_found: 'Campagna non trovata',
    error_not_launchable: 'La campagna non può essere avviata in questo stato',
    error_dpa_outdated: 'Devi accettare la versione corrente del DPA prima di avviare campagne.',
    error_not_running: 'La campagna non è in esecuzione',
    error_not_paused: 'La campagna non è in pausa',
    error_already_terminal: 'La campagna è già stata completata o annullata',
    review_title: 'Riepilogo',
    tab_all: 'Tutte',
    tab_draft: 'Bozze',
    tab_running: 'In corso',
    tab_completed: 'Completate',
    tab_cancelled: 'Annullate',
    col_name: 'Nome',
    col_script: 'Script',
    col_contacts: 'Contatti',
    col_status: 'Stato',
    col_cost: 'Costo',
    col_created: 'Creata',
    action_view: 'Visualizza',
    action_pause: 'Metti in pausa',
    action_resume: 'Riprendi',
    action_cancel: 'Annulla campagna',
    action_duplicate: 'Duplica',
    action_live: 'Vista live',
    action_results: 'Risultati',
    action_print_report: 'Stampa report',
    print_back_to_campaign: 'Torna alla campagna',
    print_action_print: 'Stampa',
    print_phones_show: 'Mostra numeri completi',
    print_phones_mask: 'Mascherare numeri',
    print_phones_full_notice: 'I numeri sono mostrati per intero.',
    print_phones_mask_notice:
      'I numeri sono mascherati: visibili solo le ultime 4 cifre.',
    print_report_label: 'Report di campagna',
    print_status_label: 'Stato',
    print_generated_at: 'Generato il {date}',
    print_summary_title: 'Riepilogo',
    print_summary_started: 'Avvio',
    print_outcomes_title: 'Esiti delle chiamate',
    print_outcomes_empty: 'Nessun esito ancora registrato.',
    print_appointments_title: 'Appuntamenti principali',
    print_appointments_empty: 'Nessun appuntamento fissato.',
    print_appt_col_contact: 'Contatto',
    print_appt_col_phone: 'Telefono',
    print_appt_col_scheduled: 'Data appuntamento',
    print_appt_col_notes: 'Note',
    first_campaign_title: 'Nessuna campagna',
    first_campaign_desc: 'Crea la tua prima campagna per iniziare a chiamare i tuoi contatti.',
    first_campaign_cta: 'Crea prima campagna',
    no_campaigns_in_tab: 'Nessuna campagna in questa categoria',
    pause_confirm_title: 'Metti in pausa la campagna',
    pause_confirm_desc:
      'Le chiamate in corso continueranno fino al termine; nessuna nuova chiamata sarà avviata.',
    cancel_confirm_title: 'Annulla la campagna',
    cancel_confirm_desc:
      "L'annullamento è immediato: le chiamate in corso verranno terminate e il credito riservato verrà rilasciato.",
    cancel_typed_confirm_hint: 'Per confermare, digita il nome della campagna qui sotto:',
    pause_success: 'Campagna messa in pausa',
    resume_success: 'Campagna ripresa',
    cancel_success: 'Campagna annullata',
    duplicate_success: 'Campagna duplicata',
    cost_estimated: 'Stima: {cost}',
    cost_actual: 'Effettivo: {cost}',
    detail_kpi_total: 'Chiamate totali',
    detail_kpi_completed: 'Completate',
    detail_kpi_failed: 'Fallite',
    detail_kpi_completion_rate: 'Tasso completamento',
    detail_kpi_qualified_leads: 'Lead qualificati',
    detail_kpi_appointments: 'Appuntamenti fissati',
    detail_kpi_credit_used: 'Credito consumato',
    detail_kpi_avg_duration: 'Durata media chiamata',
    detail_status_since: 'Dal {date}',
    detail_script_label: 'Script',
    detail_list_label: 'Lista contatti',
    detail_settings_label: 'Impostazioni campagna',
    detail_window_label: 'Finestra oraria',
    detail_concurrency_label: 'Chiamate simultanee',
    detail_started_label: 'Avviata',
    detail_completed_label: 'Completata il',
    detail_scheduled_label: 'Pianificata per',
    action_export: 'Esporta risultati',
    live_label: 'In diretta',
    live_progress_label: 'Avanzamento campagna',
    live_progress_count: '{completed}/{total} chiamate',
    live_kpis_label: 'KPI in tempo reale',
    live_kpi_in_progress: 'Chiamate in corso',
    live_kpi_completed: 'Chiamate completate',
    live_kpi_appointments: 'Appuntamenti fissati',
    live_kpi_cost: 'Costo accumulato',
    live_calls_title: 'Chiamate in tempo reale',
    live_calls_empty: 'Nessuna chiamata ancora avviata.',
    outcome_interested: 'Interessato',
    outcome_not_interested: 'Non interessato',
    outcome_appointment_booked: 'Appuntamento fissato',
    outcome_wrong_number: 'Numero errato',
    outcome_callback_requested: 'Richiamare',
    outcome_voicemail_left: 'Messaggio lasciato',
    outcome_voicemail_no_message: 'Segreteria',
    outcome_do_not_call: 'Non chiamare',
    results_subtitle: 'Risultati delle chiamate',
    results_filter_outcome: 'Esito',
    results_filter_duration: 'Durata (s)',
    results_filter_duration_min: 'Min',
    results_filter_duration_max: 'Max',
    results_filter_date: 'Data',
    results_filter_date_from: 'Da',
    results_filter_date_to: 'A',
    results_filter_clear: 'Pulisci filtri',
    results_sort_label: 'Ordina',
    results_sort_started_desc: 'Più recenti',
    results_sort_started_asc: 'Meno recenti',
    results_sort_duration_desc: 'Durata (decrescente)',
    results_sort_duration_asc: 'Durata (crescente)',
    results_sort_cost_desc: 'Costo (decrescente)',
    results_sort_cost_asc: 'Costo (crescente)',
    results_export_all: 'Esporta CSV',
    results_export_selected: 'Esporta selezionati ({count})',
    results_export_ready: 'Esportazione pronta. Download avviato.',
    results_export_deferred: "Esportazione in coda. Riceverai un'email quando il file sarà pronto.",
    results_col_contact: 'Contatto',
    results_col_phone: 'Telefono',
    results_col_status: 'Stato chiamata',
    results_col_outcome: 'Esito',
    results_col_duration: 'Durata',
    results_col_cost: 'Costo',
    results_col_started: 'Ora chiamata',
    results_action_detail: 'Dettaglio',
    results_empty: 'Nessuna chiamata registrata.',
    results_empty_filtered: 'Nessuna chiamata corrisponde ai filtri.',
  },
  errors: {
    title: 'Errore',
    message: 'Si è verificato un errore imprevisto.',
    retry: 'Riprova',
  },
  legal: {
    draft_notice: 'Documento in bozza — i contenuti sono indicativi e devono essere validati dal consulente legale prima della pubblicazione.',
    last_updated_label: 'Ultimo aggiornamento',
    effective_date_value: '1 gennaio 2026',
    back_to_home: 'Torna alla home',
    controller_label: 'Titolare del trattamento',
    controller_value: 'VoiceFlow S.r.l. — Via Esempio 1, 00100 Roma — privacy@voiceflow.example',
    privacy_title: 'Informativa sulla privacy',
    privacy_subtitle: 'Come trattiamo i dati personali degli utenti della piattaforma VoiceFlow.',
    privacy_section_controller_title: '1. Titolare del trattamento',
    privacy_section_controller_body: 'Il titolare del trattamento è VoiceFlow S.r.l.',
    privacy_section_data_collected_title: '2. Categorie di dati trattati',
    privacy_section_data_collected_body: 'Trattiamo dati identificativi, di contatto, di fatturazione e di utilizzo.',
    privacy_section_purposes_title: '3. Finalità del trattamento',
    privacy_section_purposes_body: 'I dati sono trattati per la fornitura del servizio.',
    privacy_section_legal_basis_title: '4. Base giuridica',
    privacy_section_legal_basis_body: 'Il trattamento è basato sul contratto e sul consenso.',
    privacy_section_retention_title: '5. Periodi di conservazione',
    privacy_section_retention_body: 'Le registrazioni sono conservate 12 mesi.',
    privacy_section_rights_title: "6. Diritti dell'interessato",
    privacy_section_rights_body: "L'interessato può esercitare i diritti GDPR.",
    privacy_section_processors_title: '7. Responsabili del trattamento',
    privacy_section_processors_body: 'Ci avvaliamo di responsabili esterni.',
    privacy_section_transfers_title: '8. Trasferimenti extra-UE',
    privacy_section_transfers_body: 'Trasferimenti basati su SCC.',
    privacy_section_contact_title: '9. Contatti',
    privacy_section_contact_body: 'privacy@voiceflow.example',
    dpa_title: 'Accordo sul Trattamento dei Dati (DPA)',
    dpa_subtitle: 'Accordo ai sensi dell\'Art. 28 GDPR.',
    dpa_version_label: 'Versione DPA',
    dpa_section_parties_title: '1. Parti',
    dpa_section_parties_body: 'Cliente e VoiceFlow.',
    dpa_section_subject_title: '2. Oggetto e durata',
    dpa_section_subject_body: 'Trattamento dei dati per il servizio.',
    dpa_section_data_categories_title: '3. Categorie di dati e di interessati',
    dpa_section_data_categories_body: 'Dati identificativi e di contatto.',
    dpa_section_obligations_title: '4. Obblighi del responsabile',
    dpa_section_obligations_body: 'Riservatezza e sicurezza.',
    dpa_section_subprocessors_title: '5. Sub-responsabili',
    dpa_section_subprocessors_body: 'Elenco pubblicato e notifica delle modifiche.',
    dpa_section_security_title: '6. Misure di sicurezza',
    dpa_section_security_body: 'Crittografia, RBAC, audit log.',
    dpa_section_breach_title: '7. Notifica di violazione',
    dpa_section_breach_body: 'Notifica entro 72 ore.',
    dpa_section_termination_title: '8. Cessazione',
    dpa_section_termination_body: 'Restituzione o cancellazione dei dati.',
    terms_title: 'Termini di Servizio',
    terms_subtitle: 'Condizioni generali di utilizzo della piattaforma.',
    terms_section_acceptance_title: '1. Accettazione',
    terms_section_acceptance_body: "L'utilizzo implica accettazione.",
    terms_section_service_title: '2. Descrizione del servizio',
    terms_section_service_body: 'Piattaforma SaaS di chiamate AI.',
    terms_section_account_title: '3. Account e responsabilità',
    terms_section_account_body: 'Custodia delle credenziali.',
    terms_section_acceptable_use_title: '4. Uso accettabile',
    terms_section_acceptable_use_body: 'Vietato uso illecito.',
    terms_section_billing_title: '5. Fatturazione',
    terms_section_billing_body: 'Servizio prepagato a crediti.',
    terms_section_liability_title: '6. Limitazione di responsabilità',
    terms_section_liability_body: 'Responsabilità limitata.',
    terms_section_termination_title: '7. Recesso',
    terms_section_termination_body: 'Recesso in qualsiasi momento.',
    terms_section_law_title: '8. Legge applicabile',
    terms_section_law_body: 'Legge italiana, foro di Roma.',
    cookie_title: 'Cookie Policy',
    cookie_subtitle: 'Informazioni sui cookie utilizzati dalla piattaforma.',
    cookie_section_what_title: '1. Cosa sono i cookie',
    cookie_section_what_body: 'Piccoli file di testo.',
    cookie_section_types_title: '2. Tipologie di cookie utilizzati',
    cookie_section_types_body: 'Cookie tecnici e analitici aggregati.',
    cookie_section_consent_title: '3. Consenso',
    cookie_section_consent_body: 'Cookie tecnici non richiedono consenso.',
    cookie_section_management_title: '4. Gestione dei cookie',
    cookie_section_management_body: 'Gestione tramite impostazioni del browser.',
  },
  recording_player: {
    audio_label: 'Registrazione della chiamata',
    play: 'Riproduci',
    pause: 'Pausa',
    skip_back: 'Indietro di 15 secondi',
    skip_forward: 'Avanti di 15 secondi',
    seek_label: 'Posizione di riproduzione',
    speed_group_label: 'Velocità di riproduzione',
    transcript: 'Trascrizione',
    transcript_empty: 'Trascrizione non disponibile',
    transcript_show_full: 'Mostra altri {remaining} segmenti',
    speaker_agent: 'Agente',
    speaker_caller: 'Interlocutore',
  },
  calls: {
    back_to_campaign: 'Torna alla campagna',
    back_to_dashboard: 'Torna alla dashboard',
    unknown_contact: 'Contatto sconosciuto',
    kpi_started: 'Inizio chiamata',
    kpi_duration: 'Durata',
    kpi_cost: 'Costo',
    kpi_direction: 'Direzione',
    direction_outbound: 'In uscita',
    direction_inbound: 'In entrata',
    tab_recording: 'Registrazione',
    tab_data: 'Dati strutturati',
    tab_audit: 'Audit',
    timeline_empty: 'Nessun evento registrato per questa chiamata.',
    timeline_tool: 'Strumento: {name}',
    event_call_created: 'Chiamata creata',
    event_call_dispatched: 'Chiamata inviata al provider',
    event_call_started: 'Chiamata in corso',
    event_call_ended: 'Chiamata terminata',
    event_call_tool_invoked: 'Strumento invocato',
    event_call_issue_reported: 'Problema segnalato',
    event_credit_refunded: 'Credito rimborsato',
    recording_processing: 'Registrazione in elaborazione… aggiornamento automatico in corso.',
    transcript_processing: 'Trascrizione in elaborazione… aggiornamento automatico in corso.',
    audit_forbidden: "Non hai i permessi per visualizzare l'audit log di questa chiamata.",
    audit_empty: 'Nessuna voce di audit per questa chiamata.',
    refund_action: 'Rimborsa chiamata',
    refund_dialog_title: 'Rimborsa la chiamata',
    refund_dialog_description: "Verrà accreditato {amount} sul saldo dell'organizzazione.",
    refund_reason_placeholder: 'Motivo del rimborso',
    refund_confirm: 'Conferma rimborso',
    refund_success: 'Rimborso eseguito',
    report_action: 'Segnala problema',
    report_dialog_title: 'Segnala un problema con questa chiamata',
    report_dialog_description: "Il messaggio verrà inviato al supporto.",
    report_message_placeholder: 'Descrivi il problema',
    report_confirm: 'Invia segnalazione',
    report_success: 'Segnalazione inviata al supporto',
    invalid_call_id: 'ID chiamata non valido',
    reason_required: 'Inserisci un motivo',
    reason_too_long: 'Motivo troppo lungo',
    message_required: 'Descrivi il problema',
    message_too_long: 'Messaggio troppo lungo',
    call_not_found: 'Chiamata non trovata',
    call_not_refundable: 'Questa chiamata non ha un costo addebitato',
    support_email_not_configured: 'Indirizzo di supporto non configurato.',
  },
  status: {
    draft: 'Bozza',
    scheduled: 'Pianificata',
    running: 'In corso',
    paused: 'In pausa',
    completed: 'Completata',
    cancelled: 'Annullata',
    error: 'Errore',
    pending: 'In attesa',
    dialing: 'In chiamata',
    in_progress: 'In corso',
    failed: 'Fallita',
    no_answer: 'Senza risposta',
    voicemail: 'Segreteria',
    busy: 'Occupato',
    processing: 'In elaborazione',
    succeeded: 'Completato',
    refunded: 'Rimborsato',
    active: 'Attivo',
    opted_out: 'Opt-out',
    pending_review: 'In revisione',
    compliant: 'Conforme',
    warning: 'Avviso',
    blocked: 'Bloccato',
    expired: 'Scaduto',
  },
};

vi.mock('next-intl', () => ({
  useTranslations: vi.fn((namespace: string) => {
    return (key: string, params?: Record<string, string | number>) => {
      const ns = _italianStrings[namespace];
      let msg = ns?.[key] ?? key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          msg = msg.replace(`{${k}}`, String(v));
        }
      }
      return msg;
    };
  }),
  useLocale: vi.fn(() => 'it'),
  NextIntlClientProvider: ({ children }: { children: unknown }) => children,
}));

vi.mock('next-intl/server', () => ({
  getTranslations: vi.fn(async (namespace: string) => {
    return (key: string, params?: Record<string, string | number>) => {
      const ns = _italianStrings[namespace];
      let msg = ns?.[key] ?? key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          msg = msg.replace(`{${k}}`, String(v));
        }
      }
      return msg;
    };
  }),
  getLocale: vi.fn(async () => 'it'),
}));
