import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

// jsdom does not implement ResizeObserver (used by cmdk and other UI libs)
global.ResizeObserver = class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
};

// jsdom does not implement scrollIntoView (used by cmdk)
Element.prototype.scrollIntoView ??= () => {};

// ---------------------------------------------------------------------------
// Global next-intl mock for unit tests.
//
// Components use useTranslations(namespace) which returns t(key).
// The mock returns the Italian string for each key so all existing tests that
// check for Italian UI text continue to pass without wrapping in
// NextIntlClientProvider.
// ---------------------------------------------------------------------------
const _italianStrings: Record<string, Record<string, string>> = {
  common: {
    open_menu: 'Apri menu',
    search_placeholder: 'Cerca...',
    search_label: 'Apri ricerca (Cmd+K)',
    notifications: 'Notifiche',
    expand_sidebar: 'Espandi barra laterale',
    collapse_sidebar: 'Comprimi barra laterale',
    expand: 'Espandi',
    collapse: 'Comprimi',
    mobile_nav_label: 'Menu di navigazione',
    organizations: 'Organizzazioni',
    create_new_org: 'Crea nuova organizzazione',
    org_switcher_label: 'Cambia organizzazione',
    default_org_name: 'Organizzazione',
    marketing_nav_label: 'Navigazione marketing',
    marketing_sign_in: 'Accedi',
    marketing_legal_nav_label: 'Link legali',
    marketing_copyright: '© {year} VoiceFlow. Tutti i diritti riservati.',
    marketing_privacy: 'Privacy Policy',
    marketing_terms: 'Termini di Servizio',
    marketing_cookies: 'Cookie Policy',
    command_palette_title: 'Ricerca rapida',
    command_palette_description: "Cerca azioni e naviga nell'applicazione",
    command_palette_placeholder: 'Cerca azioni...',
    command_palette_no_results: 'Nessun risultato trovato.',
    command_palette_nav_group: 'Navigazione',
    confirm: 'Conferma',
    cancel: 'Annulla',
    loading: 'Attendere…',
    error_generic: 'Si è verificato un errore. Riprova.',
  },
  nav: {
    dashboard: 'Dashboard',
    campaigns: 'Campagne',
    contacts: 'Contatti',
    scripts: 'Script',
    credit: 'Credito',
    settings: 'Impostazioni',
    primary_nav_label: 'Navigazione principale',
  },
  auth: {
    user_menu_label: 'Menu utente',
    profile: 'Profilo',
    settings: 'Impostazioni',
    language: 'Lingua',
    theme: 'Tema',
    sign_out: 'Esci',
    default_user: 'Utente',
    theme_light: 'Chiaro',
    theme_dark: 'Scuro',
    theme_system: 'Sistema',
    locale_it: 'Italiano',
    locale_en: 'English',
    sign_in: 'Accedi',
    sign_in_description: 'Accedi al tuo account',
    sign_up: 'Registrati',
    email: 'Email',
    already_have_account: 'Hai già un account?',
    no_account_yet: 'Non hai ancora un account?',
    magic_link_title: 'Accedi',
    magic_link_description: 'Inserisci la tua email e ti invieremo un link di accesso',
    send_link: 'Invia link di accesso',
    signup_title: 'Crea account',
    signup_description: 'Inserisci la tua email per creare un nuovo account',
    verify_title: 'Controlla la tua email',
    verify_description: 'Abbiamo inviato un link di accesso a {email}. Clicca sul link per accedere.',
    verify_description_generic: 'Ti abbiamo inviato un link di accesso. Controlla la tua email e clicca sul link.',
    back_to_login: 'Torna al login',
    email_required: "L'email è obbligatoria",
    email_invalid: 'Inserisci un indirizzo email valido',
    link_sent: 'Link inviato! Controlla la tua casella.',
    sending: 'Invio in corso…',
  },
  contacts: {
    title: 'Contatti',
    new_contact: 'Nuovo contatto',
    no_contacts: 'Nessun contatto trovato',
    import_contacts: 'Importa contatti',
    export_contacts: 'Esporta contatti',
    first_name: 'Nome',
    last_name: 'Cognome',
    phone: 'Telefono',
    email: 'Email',
    opted_out: 'Ha rinunciato',
    last_called: 'Ultima chiamata',
    upload_title: 'Importa contatti',
    upload_description: 'Carica un file CSV per importare i contatti nella tua organizzazione',
    step_file: 'File',
    step_mapping: 'Mappatura colonne',
    step_compliance: 'Compliance',
    drop_file_here: 'Trascina il tuo file CSV qui',
    or_click_to_browse: 'o clicca per sfogliare',
    file_size_limit: 'Massimo 50 MB',
    accepted_formats: 'Accettati: CSV, Excel, testo',
    uploading: 'Caricamento in corso…',
    upload_complete: 'Caricamento completato',
    upload_error: 'Errore nel caricamento',
    auto_detected_columns: 'Colonne rilevate automaticamente',
    map_columns_title: 'Mappa colonne',
    map_columns_description: 'Assegna le colonne del tuo CSV ai campi corretti del contatto',
    preview_rows: 'Anteprima prime righe',
    column_phone: 'Colonna telefono',
    column_first_name: 'Colonna nome',
    column_last_name: 'Colonna cognome',
    column_email: 'Colonna email',
    not_mapped: 'Non mappato',
    consent_basis_label: 'Base giuridica del trattamento',
    consent_basis_consent: 'Consenso esplicito',
    consent_basis_legitimate_interest: 'Legittimo interesse',
    consent_basis_existing_customer: 'Cliente esistente',
    contact_type_label: 'Tipo di contatto',
    contact_type_b2c: 'B2C (privati)',
    contact_type_b2b: 'B2B (aziende)',
    consent_evidence_label: 'Evidenza del consenso (opzionale)',
    consent_evidence_placeholder: 'es. iscritto tramite modulo web il 01/01/2024',
    disclaimer_text: 'Confermo di avere base giuridica per contattare questi numeri',
    disclaimer_required: 'Devi accettare la dichiarazione per procedere',
    phone_column_required: 'La colonna telefono è obbligatoria',
    submit_import: 'Avvia importazione',
    submitting_import: 'Avvio in corso…',
    import_started: 'Importazione avviata con successo',
    back: 'Indietro',
    next: 'Avanti',
    list_detail_back: 'Torna ai contatti',
    list_source_csv_upload: 'Caricamento CSV',
    list_source_api: 'API',
    list_source_zapier: 'Zapier',
    list_total_contacts: 'Totale',
    list_valid_contacts: 'Validi',
    list_parsing_title: 'Importazione in corso',
    list_parsing_description: 'Il tuo CSV è in fase di elaborazione. Potrebbe richiedere alcuni minuti.',
    list_failed_title: 'Importazione fallita',
    list_failed_description: 'Nessun contatto valido trovato nel file.',
    list_errors_download: 'Scarica report errori',
    list_errors_loading: 'Caricamento…',
    list_errors_not_found: 'Report errori non trovato',
    list_contacts_count: '{count} contatti',
    col_name: 'Nome',
    col_phone: 'Telefono',
    col_email: 'Email',
    col_opt_out: 'Opt-out',
    col_rpo: 'RPO',
    col_actions: 'Azioni',
    filter_opt_out: 'Con opt-out',
    filter_all_opt_out: 'Tutti',
    filter_rpo_status: 'Stato RPO',
    filter_all_rpo: 'Tutti gli stati',
    filter_has_email: 'Con email',
    filter_search: 'Cerca per nome o telefono',
    rpo_clear: 'Conforme',
    rpo_blocked: 'Bloccato',
    rpo_unchecked: 'Non verificato',
    action_mark_opt_out: 'Segna come opt-out',
    action_opt_out_success: 'Contatto segnato come opt-out',
    action_delete: 'Elimina contatto',
    action_delete_title: 'Elimina contatto',
    action_delete_description: 'Il contatto verrà rimosso definitivamente da questa lista.',
    action_delete_success: 'Contatto eliminato',
    action_view_metadata: 'Vedi dati originali',
    action_bulk_delete_description: 'Elimina {count} contatti. Questa operazione non può essere annullata.',
    bulk_mark_opt_out: 'Segna come opt-out',
    bulk_delete: 'Elimina selezionati',
    bulk_selected: '{count} selezionati',
    bulk_opt_out_success: '{count} contatti segnati come opt-out',
    bulk_delete_success: '{count} contatti eliminati',
    export_selected: 'Esporta selezionati ({count})',
    no_contacts_in_list: 'Nessun contatto in questa lista',
    no_contacts_match: 'Nessun contatto corrisponde ai filtri',
    status_opted_out: 'Opt-out',
    status_active: 'Attivo',
    tab_lists: 'Liste',
    tab_all: 'Tutti i contatti',
    tab_opt_out: 'Opt-out',
    upload_new_list: 'Carica nuova lista',
    no_lists: 'Nessuna lista trovata',
    list_col_name: 'Nome',
    list_col_source: 'Fonte',
    list_col_contacts: 'Contatti',
    list_col_status: 'Stato',
    list_col_created: 'Data creazione',
    all_contacts_title: 'Tutti i contatti',
    opt_out_title: 'Contatti con opt-out',
    add_contact_btn: 'Aggiungi contatto',
    add_contact_dialog_title: 'Aggiungi contatto manualmente',
    add_contact_phone_placeholder: '+39 333 1234567',
    add_contact_phone_invalid: 'Numero di telefono non valido',
    add_contact_success: 'Contatto aggiunto',
    add_contact_already_exists: 'Contatto già presente — dati aggiornati',
    add_contact_submitting: 'Salvataggio…',
    dnc_btn: 'Importa do-not-call',
    dnc_dialog_title: 'Importa lista do-not-call',
    dnc_dialog_description: 'Carica un CSV con un numero di telefono per riga. Nessun contatto viene creato — solo gli opt-out vengono registrati.',
    dnc_file_label: 'File CSV (un numero per riga)',
    dnc_paste_label: 'Oppure incolla i numeri',
    dnc_paste_placeholder: '+39 333 1234567\n+39 02 12345678\n…',
    dnc_submit: 'Importa',
    dnc_submitting: 'Importazione…',
    dnc_success: '{count} numeri aggiunti alla lista do-not-call',
    dnc_no_valid_numbers: 'Nessun numero valido trovato nel file',
    dnc_error: "Errore durante l'importazione",
    export_btn: 'Esporta CSV',
    export_exporting: 'Esportazione…',
    export_success: 'Esportazione completata — il download inizierà a breve',
    export_deferred: 'Esportazione avviata — riceverai una notifica al completamento',
    export_error: "Errore durante l'esportazione",
  },
  credit: {
    top_up: 'Ricarica',
    total_purchased: 'Totale acquistati',
    credit_balance_label: 'Saldo crediti',
    reserved_active_calls: 'Riservati (chiamate attive)',
    available: 'Disponibili',
    pill_aria_label: 'Saldo crediti: {minutes} minuti rimanenti',
    topup_title: 'Ricarica credito',
    topup_subtitle: 'Scegli il pacchetto più adatto alle tue esigenze',
    per_minute: '€{rate}/min',
    included_minutes_fmt: '{minutes} minuti',
    proceed_to_payment: 'Procedi al pagamento',
    processing: 'Elaborazione…',
    payment_cancelled: 'Pagamento annullato',
    recommended_test: 'Ideale per testare il servizio',
    recommended_starter: 'Concessionario piccolo',
    recommended_growth: 'Concessionario medio',
    recommended_scale: 'Grande concessionario o rete',
    vat_included: 'IVA inclusa',
    topup_success_title: 'Pagamento completato',
    topup_success_subtitle: 'Il tuo saldo è stato aggiornato. Puoi iniziare ad utilizzare i tuoi crediti.',
    topup_success_balance: '{minutes} minuti disponibili',
    topup_success_cta: 'Vai alla dashboard',
    topup_pending_title: 'Verifica pagamento in corso…',
    topup_pending_subtitle: 'Attendi mentre confermiamo il tuo pagamento.',
    topup_timeout_title: 'Pagamento in elaborazione',
    topup_timeout_message: 'Riceverai un\'email appena il pagamento è confermato.',
    topup_session_not_found: 'Sessione non trovata.',
    topup_back_to_topup: 'Torna alla ricarica',
    page_title: 'Credito',
    top_up_cta: 'Ricarica',
    balance_minutes: '{minutes} minuti',
    balance_cents: '€{euros}',
    package_pools_title: 'Pacchetti acquistati',
    pool_purchased_on: 'Acquistato il {date}',
    ledger_title: 'Storico movimenti',
    ledger_col_type: 'Tipo',
    ledger_col_description: 'Descrizione',
    ledger_col_delta: 'Importo',
    ledger_col_balance: 'Saldo dopo',
    ledger_col_date: 'Data',
    ledger_no_entries: 'Nessun movimento',
    filter_all_types: 'Tutti i tipi',
    filter_type_topup: 'Ricarica',
    filter_type_reservation: 'Prenotazione',
    filter_type_release: 'Rilascio',
    filter_type_charge: 'Addebito',
    filter_type_refund: 'Rimborso',
    filter_type_adjustment: 'Rettifica',
    filter_date_from: 'Da',
    filter_date_to: 'A',
    export_csv: 'Esporta CSV',
    ledger_col_invoice: 'Fattura',
    invoice_link: 'Scarica',
    ledger_count: '{count} movimenti',
  },
  table: {
    columns: 'Colonne',
    visible_columns: 'Colonne visibili',
    rows_per_page: 'Righe per pagina',
    rows_selected: '{selected} di {total} riga/e selezionata/e',
    total_rows: '{total} riga/e totali',
    page_of: 'Pagina {page} di {total}',
    first_page: 'Prima pagina',
    prev_page: 'Pagina precedente',
    next_page: 'Pagina successiva',
    last_page: 'Ultima pagina',
  },
  onboarding: {
    title: 'Configura la tua organizzazione',
    description: 'Raccontaci della tua organizzazione per iniziare.',
    name_label: 'Nome organizzazione',
    name_placeholder: 'Acme Corp',
    legal_name_label: 'Ragione sociale (opzionale)',
    legal_name_placeholder: 'Acme S.r.l.',
    vat_label: 'Partita IVA (opzionale)',
    vat_placeholder: '12345678901',
    country_label: 'Paese',
    country_it: 'Italia',
    dpa_label_before: 'Accetto il ',
    dpa_link_text: 'Accordo sul Trattamento dei Dati',
    submit: 'Crea organizzazione',
    submitting: 'Creazione in corso…',
    name_required: "Il nome dell'organizzazione è obbligatorio",
    name_too_long: 'Il nome deve essere al massimo 100 caratteri',
    vat_invalid: 'Partita IVA non valida (deve essere 11 cifre con checksum valido)',
    dpa_required: "Devi accettare l'Accordo sul Trattamento dei Dati",
  },
  settings: {
    title: 'Impostazioni',
    organization: 'Organizzazione',
    members: 'Membri',
    billing: 'Fatturazione',
    profile: 'Profilo',
    notifications: 'Notifiche',
    security: 'Sicurezza',
    invite_member: 'Invita membro',
    remove_member: 'Rimuovi membro',
    role_owner: 'Proprietario',
    role_admin: 'Amministratore',
    role_operator: 'Operatore',
    role_viewer: 'Visualizzatore',
    members_title: 'Membri',
    members_description: 'Gestisci i membri del team e i loro ruoli.',
    invite_dialog_title: 'Invita un membro del team',
    invite_email_label: 'Indirizzo email',
    invite_role_label: 'Ruolo',
    invite_submit: 'Invia invito',
    invite_submitting: 'Invio in corso…',
    change_role: 'Cambia ruolo',
    change_role_dialog_title: 'Cambia ruolo del membro',
    change_role_submit: 'Salva',
    remove_confirm_title: 'Rimuovi membro',
    remove_confirm_description:
      "Il membro perderà l'accesso all'organizzazione. Questa operazione non può essere annullata.",
    column_member: 'Membro',
    column_role: 'Ruolo',
    column_joined: 'Iscritto',
    column_last_login: 'Ultimo accesso',
    column_actions: 'Azioni',
    accepted_members_title: 'Membri attivi',
    pending_invites_title: 'Inviti in sospeso',
    no_members: 'Nessun membro attivo',
    no_pending_invites: 'Nessun invito in sospeso',
    last_login_never: 'Mai',
    invited_date: 'Invitato',
    member_actions_label: 'Azioni membro',
    org_title: 'Organizzazione',
    org_description: 'Gestisci le impostazioni della tua organizzazione.',
    org_info_id: 'ID organizzazione',
    org_info_created: 'Creata il',
    org_info_members: 'Membri',
    org_name_label: 'Nome organizzazione',
    org_legal_name_label: 'Ragione sociale (opzionale)',
    org_legal_name_placeholder: 'Acme S.r.l.',
    org_vat_label: 'Partita IVA (opzionale)',
    org_vat_placeholder: '12345678901',
    org_save_button: 'Salva modifiche',
    org_save_submitting: 'Salvataggio…',
    org_danger_zone_title: 'Zona pericolosa',
    org_danger_zone_description:
      "L'eliminazione dell'organizzazione è permanente e rimuoverà tutti i dati.",
    org_delete_button: 'Elimina organizzazione',
    org_delete_dialog_title: 'Elimina organizzazione',
    org_delete_dialog_description: 'Questo eliminerà logicamente "{name}".',
    org_delete_confirm_label: "Digita il nome dell'organizzazione per confermare",
    org_delete_submitting: 'Eliminazione…',
    billing_portal_title: 'Storico fatture',
    billing_portal_description: 'Accedi al portale di fatturazione.',
    billing_portal_button: 'Apri storico fatture',
    billing_portal_opening: 'Apertura in corso…',
  },
  integrations: {
    pat_title: 'Token di Accesso Personale',
    pat_description: 'Token per accesso programmatico all\'API.',
    create_token: 'Crea token',
    create_token_dialog_title: 'Crea Token di Accesso Personale',
    token_name_label: 'Nome del token',
    token_name_placeholder: 'es. Integrazione Zapier',
    create_token_submit: 'Crea',
    create_token_submitting: 'Creazione in corso…',
    token_created_title: 'Token creato',
    token_created_description: 'Copia il token ora. Non potrai vederlo di nuovo.',
    copy_token: 'Copia token',
    revoke: 'Revoca',
    column_name: 'Nome',
    column_prefix: 'Prefisso',
    column_scopes: 'Ambiti',
    column_last_used: 'Ultimo utilizzo',
    column_created: 'Creato',
    column_actions: 'Azioni',
    no_tokens: 'Nessun token di accesso personale',
    never_used: 'Mai',
  },
  errors: {
    title: 'Errore',
    message: 'Si è verificato un errore imprevisto.',
    retry: 'Riprova',
  },
  status: {
    draft: 'Bozza',
    scheduled: 'Pianificata',
    running: 'In corso',
    paused: 'In pausa',
    completed: 'Completata',
    cancelled: 'Annullata',
    error: 'Errore',
    pending: 'In attesa',
    dialing: 'In chiamata',
    in_progress: 'In corso',
    failed: 'Fallita',
    no_answer: 'Senza risposta',
    voicemail: 'Segreteria',
    busy: 'Occupato',
    processing: 'In elaborazione',
    succeeded: 'Completato',
    refunded: 'Rimborsato',
    active: 'Attivo',
    opted_out: 'Opt-out',
    pending_review: 'In revisione',
    compliant: 'Conforme',
    warning: 'Avviso',
    blocked: 'Bloccato',
    expired: 'Scaduto',
  },
};

vi.mock('next-intl', () => ({
  useTranslations: vi.fn((namespace: string) => {
    return (key: string, params?: Record<string, string | number>) => {
      const ns = _italianStrings[namespace];
      let msg = ns?.[key] ?? key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          msg = msg.replace(`{${k}}`, String(v));
        }
      }
      return msg;
    };
  }),
  useLocale: vi.fn(() => 'it'),
  NextIntlClientProvider: ({ children }: { children: unknown }) => children,
}));
